README.md, package.json
=> - Add npm dependency badges to main readme

.travis.yml, README.md, gulpfile.js, package.json
- Add devDependency for coveralls
- Update travis to send lcov results to coveralls after build
- Add coverage badge to main readme
- Update instanbul remap to output lcov
Fixes #9
=> Integrate coverage into CI pipeline

README.md
=> Move badges in readme after title following more common repositories

examples/web/assets/js/app.js, examples/web/index.html, src/Default/default.ts, src/Electron/electron.ts, src/OpenFin/openfin.ts, src/container.ts, src/window.ts, tests/unit/Default/default.spec.ts, tests/unit/Electron/electron.spec.ts, tests/unit/OpenFin/openfin.spec.ts, tests/unit/container.spec.ts
Add loadLayout, saveLayout and getLayouts to ContainerWindowManager and implement in each container
Resolves #14
=> Window layout persistence

codecov.yml
- Increase upper range to 95
- Change PR comment to not show graph
- Change PR comment to "new" behavior which is to delete the old comment and post a new one rather than edit existing
=> Update codecov integration settings

.vscode/settings.json, gulpfile.js, package.json, tsconfig-staging.json
=> Generate declarations (.d.ts)

gulpfile.js
-  Generate iffe/desktop.js bundle to be used by v8 extensions (can't use umd)
- Wrap umd desktop.js with a condition to skip redeclaring if desktopJS is already defined.  This is for when desktopJS will be preloaded by the container and we don't want the script included by a hosted page to redeclare.
- Cleanup any references of "dist" output folder to use the variable
=> Update bundle output

CODEOWNERS
https://github.com/blog/2392-introducing-code-owners
=> Add CODEOWNERS with default reviewer of @Morgan-Stanley/desktopjs-core

src/Default/default.ts, src/Electron/electron.ts, src/OpenFin/openfin.ts, src/window.ts, tests/unit/Default/default.spec.ts, tests/unit/Electron/electron.spec.ts, tests/unit/OpenFin/openfin.spec.ts
=> ContainerWindow getBounds/setBounds

src/Default/default.ts, tests/unit/Default/default.spec.ts
=> Change message bus unsubscribe event driver

examples/electron/electron.js
=> fix for issue65, js error on startup

examples/web/assets/js/app.js
=> Change notification example to use traditional callback rather than new promise based api

examples/web/index.html
=> Use Electron FAQ documented workaround for using jQuery

gulpfile.js
- Have watch task build project first
- Add root json and js files to watch glob in order to rebuild on changes to package/tsconfig/tslint or gulpfile.
=> Gulp watch enhancements

examples/electron/electron.js, examples/web/assets/js/app.js, src/Electron/electron.ts, tests/unit/Electron/electron.spec.ts
=> Fix ElectronContainer getMainWindow()

examples/web/assets/css/app.css, examples/web/assets/js/app.js, examples/web/index.html
=> Add fps display via simple requestAnimationFrame based calculation to status bar on example application

src/window.ts, tests/unit/window.spec.ts, tslint.json
Applicable for OpenFin and Electron
=> Add support for auto window grouping upon completion of snap docking

src/desktop.ts
This will allow for easier custom container implementations from class reuse.
=> Add ContainerNotification and ObjectTransform to default exports

package.json
=> chore(package): update gulp-typescript to version 4.0.1

package.json
=> chore(package): update typedoc to version 0.11.1

gulpfile.js, package.json
=> Remove unnecessary devDependencies

src/OpenFin/openfin.ts, src/events.ts, tests/unit/OpenFin/openfin.spec.ts
=> Filter OpenFin bounds-changing events into resize and move

src/OpenFin/openfin.ts
Notifications for when window is resizing and not when complete
=> Map resize event to OpenFin "bounds-changing"

packages/desktopjs/src/window.ts
Load time access of the DOM causes cefsharp/chromium process to crash when loading library as a v8 extension.
=> Replace load time declaration of fin variable with a run-time function

README.md, examples/electron/README.md
- Documentation links in main readme
- Missing includes in Electron example
Fixes #233
=> Fix missed readme updates from lerna monorepo refactor

package-lock.json, package.json
=> Greenkeeper/rollup 1.11.3

.vscode/tasks.json, README.md, package.json
* Add postinstall to run lerna bootstrap
* Update readme to reflect using "npm start" for local hosting
* Fix build task and remove non-working analysis task and watch task which shouldn't be a task as it would run indefinitely not allowing any other tasks
Fixes #242
=> Fix developer experience for local building

packages/desktopjs-openfin/src/openfin.ts
=> Map close event to OpenFin closing

examples/electron/package-lock.json, examples/electron/package.json, examples/web/assets/js/app.js
Remove dependency and provide suggestion as commented out polyfill in example web app.js
=> Remove electron-notify dep from examples

packages/desktopjs-electron/src/electron.ts, packages/desktopjs-electron/tests/electron.spec.ts, packages/desktopjs-openfin/src/openfin.ts, packages/desktopjs-openfin/tests/openfin.spec.ts, packages/desktopjs/src/Default/default.ts, packages/desktopjs/src/container.ts, packages/desktopjs/tests/unit/Default/default.spec.ts, packages/desktopjs/tests/unit/container.spec.ts
Add container getInfo member to obtain information about underlying container
Fixes #276
=> Add container getInfo

package-lock.json, package.json
=> Greenkeeper/rollup 1.27.0

package-lock.json, package.json, packages/desktopjs-electron/package-lock.json, packages/desktopjs-electron/package.json, packages/desktopjs-openfin/package-lock.json, packages/desktopjs-openfin/package.json
* Bump typedoc from 0.15.6 to 0.16.9
* Bump gulp-typedoc from 2.0.2 to 2.2.4
* Bump typescript from 3.5.3 to 3.7.5
* Refactor and update @types/node to root at 13.5.0
=> npm updates

.gulp/tasks/compress.js, packages/desktopjs-electron/gulpfile.js, packages/desktopjs-openfin/gulpfile.js, packages/desktopjs/gulpfile.js
=> Include iffe output in compress task

packages/desktopjs/src/Default/default.ts
=> Switch to innerHeight and innerWidth when building layout

packages/desktopjs/tests/unit/Default/default.spec.ts
=> Remove no longer required origin check as it is done by browser

.gulp/tasks/tests.js
=> Exit test with explicit error code on jasmine error

.gulp/tasks/build.js, .gulp/tasks/stage.js, .vscode/extensions.json, .vscode/tasks.json
* Fix vscode tasks
* Add eslint as recommended extension
* Fix #384
=> Developer quality of life improvements for build and testing

.github/workflows/continuous-integration.yml
v1 is being sunset in a few months - https://github.com/marketplace/actions/codecov
=> Update codecov-action to v2

packages/desktopjs/src/Default/default.ts
=> Check for window being defined during window.open shim

.gitignore, .npmrc, package-lock.json
Rely on dependabot for granular updates to package lock
=> Add back package-lock and npmrc for repeatable builds
