morganstanley/desktopJS

src/OpenFin/openfin.ts
tests/unit/OpenFin/openfin.spec.ts

- If menu will show off monitor, show left or up where appropriate
- Replace simple string concat with template literals
- Change menuHtml to public.  While this is still a stop gap until menu is supported natively by OpenFin, this at least allows some customization by devs.
- Remove unused styles from menu html
- Remove some whitespace from multiline template literal of html to reduce non minified file size
Windows showing icon:
Windows hidden icon : 
OS X:
Fixes #2

For OpenFin tray icon context menu polyfill, use monitor rect to determine whether to show menu down or up

---

examples/web/assets/js/app.js
src/OpenFin/openfin.ts
tests/unit/OpenFin/openfin.spec.ts

Since OpenFin requires a name for a window, OpenFinContainer.showWindow was defaulting the name to the url when none was provided.  This is very restricting and a large assumption for window reuse.  This changes that default when no name is provided to a unique Guid which will enable a new window for each showWindow invoked.

Change default OpenFin window name from url to new Guid

---

src/Default/default.ts
src/Electron/electron.ts
src/OpenFin/openfin.ts
src/window.ts
tests/unit/Default/default.spec.ts
tests/unit/Electron/electron.spec.ts
tests/unit/OpenFin/openfin.spec.ts

- Add and implement ContainerWindow.close()
- Hygiene for ElectronContainerWindow members to use Promise.resolve()

Add close() to ContainerWindow interface and implement for each container

---

codecov.yml

The 'new' style was too noisy as it was posting on every comment and not just commit.

Change codecov PR commenting back to default

---

examples/electron/README.md
examples/electron/electron.js
examples/web/assets/js/app.js
src/Default/default.ts
src/Electron/electron.ts
src/Minuet/minuet.ts
src/OpenFin/openfin.ts
src/container.ts
src/window.ts
tests/unit/Default/default.spec.ts
tests/unit/Electron/electron.spec.ts
tests/unit/Minuet/minuet.spec.ts
tests/unit/OpenFin/openfin.spec.ts
tests/unit/container.spec.ts

While testing auto show it became apparent that showWindow is misleading.  Renaming showWindow to createWindow and standardizing on the option "show" for auto show across OpenFin and Electron.

Refactor showWindow to createWindow

---

gulpfile.js

Upon end of gulp typedoc, force sync file creation of an empty .nojekyll file in docs directory

---

examples/electron/README.md
examples/electron/package.json
examples/web/assets/js/app.js
examples/web/notification.html
src/Default/default.ts
src/Electron/electron.ts
src/OpenFin/openfin.ts
src/container.ts
src/notification.ts
tests/unit/Electron/electron.spec.ts
tests/unit/OpenFin/openfin.spec.ts
tslint.json

- Update example Electron notification polyfill to use electron-notify instead of node-notifier
- Change web example to use W3C notification api instead of container.showNotification directly
- Change showNotification signature to match notification constructor parameters (separate title parameter)
- Change NotificationsOptions message to body to be consistent with W3C notifications and not any particular container.  This requires transforming properties for OpenFin notifications.
- Update OpenFin example notification.html to display notification message in toast
- Polyfill notification api in OpenFin and Electron to invoke common container.showNotification
- Change base class of ElectronContainer to WebContainerBase to get "globalWindow" property via dependency injection (for unit tests) …

Implement W3C Web Notification API

---

src/OpenFin/openfin.ts
tests/unit/OpenFin/openfin.spec.ts

OpenFin getMainWindow:
- Use Application.getCurrent().getWindow() in place of Window.getCurrent().getParentWindow()
OpenFin getAllWindows:
- Fix bug with adding current window to list instead of the main parent window.
Fixes #41

Use fin.desktop.Application.getCurrent().getWindow() 

---

.travis.yml
gulpfile.js

Local builds were too slow having to generate unnecessary docs every time

Remove doc generation from default bundle since it slows down the build and move to Travis CI as a second script step

---

src/Default/default.ts
src/Electron/electron.ts
src/OpenFin/openfin.ts
src/events.ts
src/window.ts
tests/unit/Default/default.spec.ts
tests/unit/Electron/electron.spec.ts
tests/unit/OpenFin/openfin.spec.ts
tests/unit/events.spec.ts

- Add abstract EventEmitter
- Change ContainerWindow from interface to abstract class extending EventEmitter
- Change concrete ContainerWindow subclasses to now extend ContainerWindow vs implement

Add instance event handlers to ContainerWindow

---

src/Default/default.ts
src/Electron/electron.ts
src/OpenFin/openfin.ts
src/window.ts
tests/unit/Default/default.spec.ts
tests/unit/Electron/electron.spec.ts
tests/unit/OpenFin/openfin.spec.ts

Avoid confusion of type ContainerWindow having a property containerWindow which is the concrete internal window and nothing related to the type ContainerWindow at all.

Rename ContainerWindow containerWindow to innerWindow

---

examples/web/assets/js/app.js
src/Default/default.ts
src/Electron/electron.ts
src/OpenFin/openfin.ts
src/container.ts
src/events.ts
tests/unit/Default/default.spec.ts
tests/unit/Electron/electron.spec.ts
tests/unit/OpenFin/openfin.spec.ts
tests/unit/container.spec.ts
tests/unit/events.spec.ts

- Extend EventEmitter
- Add window-created, layout-saved, layout-loaded events
- Overide addListener, removeListener and emit to provide custom union type event args

Create event framework for container instances

---

examples/web/assets/js/app.js
src/Default/default.ts
src/Electron/electron.ts
src/OpenFin/openfin.ts
src/container.ts
src/desktop.ts
src/events.ts
tests/unit/OpenFin/openfin.spec.ts
tests/unit/container.spec.ts
tslint.json

Propagating of emitted events over ipc/MessageBus to other windows in the container (or to main process in Electron).
app.js:
- Update example application to add simple static event subscriptions with logging
default.ts:
- Add some conditional checks brought on by some difficulty with unit test mocking.
- Emit "window-created" static event when creating a new window.
electron.ts:
- Add some conditional checks brought on by some difficulty with unit test mocking.
- When  testing the event args of the window-created event it was noticed that the widow name was incorrectly the url which had been changed in OpenFin a while back but not changed for Electron.
- Emit "window-created" static event when creating a new window.
openfin.ts:
- Emit "window-created" static event when creating a new …

Add support for static events

---

.travis.yml
package.json

.travis.yml:
- Configure npm publish from my own email/authtoken.  Will revisit on whether we want this from a single shared account but concerned about securing for now as that will intrinsically mean sharing of a key with n devs.
package.json:
- publish to orgs is private by default.  Change default so that npm publish from travis to @morgan-stanley scope will work.
Fixes #61

Configure travis for publishing to npm on source tag

---

examples/web/assets/js/app.js
src/Default/default.ts
src/Electron/electron.ts
src/OpenFin/openfin.ts
src/container.ts
src/desktop.ts
src/events.ts
src/window.ts
tests/unit/container.spec.ts
tests/unit/events.spec.ts
tests/unit/window.spec.ts

Events are passed via ipc/messagebus to other windows so events are emitted in each renderer as though they are local.
container.ts:
- Refactor move WindowEventArgs to window.ts
- Simplify static events in Container by updating EventEmitter to have the static implementation rather than use a private instance of EventEmitter within Container.
desktop.ts:
- Add ContainerWindow class on default export
events.ts:
- Implement static events on EventEmitter itself.  All static events will be centrally maintained here.
window.ts:
- Add decorator static event members (add, remove, emit, listeners)

Add ContainerWindow static event framework

---

.gitignore
package.json

package.json:
- Fix missing space that npm insists on always fixing
.gitignore
- Ignore package-lock (npm ^5 and shrinkwrap) as we don't want to pin to
corporate npm registries.

Fix spacing in package.json and ignore package-lock

---

src/desktop.ts

The singleton can always be retrieved via resolveContainer().
Fixes #59

Remove confusing "container" global export.

---

src/Default/default.ts
src/Electron/electron.ts
src/OpenFin/openfin.ts
src/container.ts
src/window.ts
tests/unit/Default/default.spec.ts
tests/unit/Electron/electron.spec.ts
tests/unit/OpenFin/openfin.spec.ts

- Add getWindow to ContainerWindowManager and implement in each supported concrete container
- Add decorator name/id fields for each concrete ContainerWindow.  While this isn't required for getWindow it is useful for retrieving the id of existing windows.
Fixes #56

Add container.getWindow(id)

---

README.md

Change relative examples link to absolute to ensure it works when viewing the readme under npmjs and github.io.

---

gulpfile.js
package.json
src/desktop.ts
tests/unit/desktop.spec.ts

Replacement is done on incoming source by rollup.  Since unit test build is currently not built by rollup we can not check for replacement in tests.

Add version property to default export (eg: desktopJS.version)

---

examples/electron/electron.js
src/Electron/electron.ts
tests/unit/Electron/electron.spec.ts

On ElectronMessageBus publish, if the current ipc has no send (eg: main process) then invoke the listeners directly

---

examples/electron/electron.js
examples/web/assets/js/app.js
src/Electron/electron.ts
src/OpenFin/openfin.ts
src/desktop.ts
src/window.ts
tests/unit/OpenFin/openfin.spec.ts
tests/unit/window.spec.ts
tslint.json

electron.js:
- Update Electron bootstrap sample to create SnapAssistWindowManager
app.js:
- Update web sample to create SnapAssistWindowManager when running under OpenFin main window
desktop.ts:
- Export SnapAssistWindowManager
window.ts:
- Add core implementation of window snapping via SnapAssistWindowManager.
openfin.ts:
- Window created event needs to be fired on callback from underlying new window OpenFin API
electron.ts:
- Change implementation of getBounds to return a Rectangle instead of using duck typing

Basic window snapping assist

---

src/Electron/electron.ts
src/window.ts
tests/unit/Electron/electron.spec.ts
tests/unit/window.spec.ts

window.ts:
- For OpenFin, use frameless api and leverage disabled-frame-bounds-changing event vs bounds-changing.  Fixes #101
- When enumerating windows in which to snap against, ignore windows in which the moving window is already grouped
electron.ts:
- ElectronContainerWindow grouping functions did not work in main process.  If running in main call methods directly instead of trying to go via ipc. Fixes #102

Refactor SnapAssistWindowManager move handler

---

examples/electron/README.md
examples/electron/electron.js
examples/web/assets/js/app.js
src/Default/default.ts
src/Electron/electron.ts
src/OpenFin/openfin.ts
src/container.ts
src/window.ts
tests/unit/Default/default.spec.ts
tests/unit/Electron/electron.spec.ts
tests/unit/OpenFin/openfin.spec.ts
tests/unit/container.spec.ts

Applies to OpenFin and Electron.  This is a breaking change as it requires an api change to createWindow to be promised based since OpenFin windows are not initialized upon return and many members can be a no-op if invoked.
container:
- Set bounds of main window when loading layout.
- If groups exist for a persisted window, restore after window is created.
- Change createWindow from synchronous to promise based
window:
- Add additional properties required for persisting main windowbounds and groups
- Change createWindow from synchronous to promise based
default: 
- Change createWindow from synchronous to promise based
electron, openfin:
- Add persistence of groups to layout
- Change createWindow from synchronous to promise based
openfin:
- Save current url of window in layout and not url …

Persist window grouping in window layouts

---

src/OpenFin/openfin.ts
src/container.ts
tests/unit/container.spec.ts

container:ts:
- Due to async OpenFin joinGroup, first build and de-dupe window groupings before joining windows to prevent race condition on joins.  Fixes #117
openfin.ts:
- OpenFin sometimes returns null for getNativeWindow(). If this happens, fallback to url provided when opening the window.  Fixes #118

Fix issues with persisting OpenFin layouts and groupings

---

src/notification.ts

NotificationPermission is defined as "default" | "denied" | "granted". This fixes dev time type check issue on callback from requestPermission.

Change type of ContainerNotification.permission from string to type alias NotificationPermission

---

src/Default/default.ts
src/Electron/electron.ts
src/container.ts
tests/unit/Default/default.spec.ts

container.ts:
- Default window.open shim for all containers
default.ts:
- Refactor bulk of createWindow into onOpen to share code paths for window.open and createWindow

Shim window.open to allow for container to know about the windows

---

src/registry.ts
tests/unit/registry.spec.ts

registry:
- Add clearRegistry to remove all container registrations
- Change internal list of containerRegistrations to a Map
registry.spec:
- Add teardown after each test to clear the registry so side effects of registrations from other tests can not impact subsequent tests
Fixes #146

Fix failing registry tests

---

tests/unit/registry.spec.ts

- Clear registry cache before each test instead of after
- Mock internal container cached value when testing cached workflow to avoid race condition changing underlying value
- Change TestContainer to have a condition that won't always resolve true unless matching option conditions are provided

Fix registry tests

---

src/Electron/electron.ts
src/OpenFin/openfin.ts

* Add options support to factory create for ElectronContainer
* For OpenFin and Electron look for options.replaceNotificationApi on optional options to override default behavior

Allow override of default behavior of registring W3C notification api with options to resolveContainer

---

src/Electron/electron.ts
src/OpenFin/openfin.ts
src/container.ts
tests/unit/Electron/electron.spec.ts
tests/unit/OpenFin/openfin.spec.ts

In Electron we are no longer able to link a BrowserWindowProxy created via window.open to a BrowserWindow instance via guestID so instead use the app level browser-window-created event and webcontents.id to correlate to new windows.  Since OpenFin also has application events, change to make consistent across both containers.
Fixes #155

Propagate Electron and OpenFin application level window created events instead of emitting our own

---

src/container.ts
src/window.ts
tests/unit/OpenFin/openfin.spec.ts
tests/unit/container.spec.ts
tests/unit/window.spec.ts

Many tests while passing and providing adequate coverage were logging promise rejects.

Cleanup async reject errors in tests

---

tests/unit/Electron/electron.spec.ts

Intermittent behavior based on parallel tests.  This will decrease coverage until rewritten and added back.

Disable test that has random coverage based on race condition

---

examples/electron/electron.js
examples/web/assets/js/app.js
src/OpenFin/openfin.ts
src/container.ts
tests/unit/OpenFin/openfin.spec.ts
tests/unit/container.spec.ts

Except for OpenFin, default implementation provided simply redirects to console.<level>.

Add simple facade for logging

---

src/Electron/electron.ts
tests/unit/Electron/electron.spec.ts

Implementation simply delegates to Electron.  This still requires a polyfill to be provided (example in app.js) for Windows 7

Provide default implementation of showNotification for Electron

---

src/window.ts
tests/unit/window.spec.ts

A lower range makes it easier to break the snap on Electron which had a tendency to be too sticky.  This is a significant improvement for #116 but it still needs future work.

Lower the snap threshold range

---

src/OpenFin/openfin.ts

Remove unnecessary padding when menu has only one item due to minimum size being forced by default with smallWindow not enabled
http://cdn.openfin.co/jsdocs/stable/fin.desktop.Window.html#~options
Before:
After:

Enable smallWindow on OpenFin tray icon context menu window

---

src/Default/default.ts
src/Electron/electron.ts
src/OpenFin/openfin.ts
src/desktop.ts

Add MessageBusSubscription and MessageBusOptions to default exports for developer usage

Refactor containers to use factory method for creating the message bus

---

src/Electron/electron.ts

The GroupWindowManager attaches events to new windows as they are created. The event for window created is fired and provides a window id. Electron has not registered the window internally yet when this event is fired so any attempt to get a reference to the Electron BrowserWindow instance from within the event handler via fromId does not work. The group manager is currently working incorrectly since an undefined window causes it to attach handlers to every window as though it is initial setup. This is causing duplicate handlers.

Fire window-created events for ElectronContainer at the end of the current event loop cycle

---

src/Electron/electron.ts
src/OpenFin/openfin.ts
src/container.ts
src/events.ts
src/window.ts
tests/unit/Electron/electron.spec.ts
tests/unit/OpenFin/openfin.spec.ts
tests/unit/events.spec.ts

Delegate beforeunload event on concrete ContainerWindow to either underlying container implementation or window object.  This pattern will facilitate creating your own non window based beforeunload in custom ContainerWindow derivations.
Follows semantics of window beforeunload by leveraging returnValue on the event argument.
```
container.getCurrentWindow().addListener("beforeunload", (e) => {
e.returnValue = false;  // Cancel closing of the window
});
```

Add beforeunload as first class window event

---

src/Default/default.ts
tests/unit/Default/default.spec.ts

Incorrect assumption that all messages received are from desktopJS and are serialized JSON.  Remove use of JSON completely so no parse is required and we can look at source to determine whether they are within scope of desktopJS message bus.

Remove json assumption from postMessage handler

---

.npmrc
examples/electron/.npmrc

Specify project level registry to override local global settings for users that are in an environment with their own private registry.  This will allow the package-lock to be added and provide more certainty that by default the registry for any new packages will stay npmjs.

Add project .npmrc to specify npmjs registry

---

examples/web/assets/js/app.js
src/Default/default.ts
src/Electron/electron.ts
src/OpenFin/openfin.ts
src/container.ts
src/window.ts
tests/unit/Default/default.spec.ts
tests/unit/Electron/electron.spec.ts
tests/unit/OpenFin/openfin.spec.ts
tests/unit/container.spec.ts
tests/unit/window.spec.ts

State will be provided back to the window upon layout load.  If the underlying native js window has getState/setState defined they will be invoked.

Add ability for windows to save custom state as part of the persisted window layout

---

packages/desktopjs-electron/src/electron.ts
packages/desktopjs-electron/tests/electron.spec.ts
packages/desktopjs-openfin/src/openfin.ts
packages/desktopjs-openfin/tests/openfin.spec.ts
packages/desktopjs/src/window.ts
packages/desktopjs/tests/unit/window.spec.ts

Raise z-order of a window without activating.  Default implementation will fallback to invoking focus() for containers in which it is not supported.

Add window.bringToFront()

---

packages/desktopjs/package-lock.json
packages/desktopjs/package.json

Until the core desktopJS package has its own readme, copy down the main readme during publish

---

packages/desktopjs/src/window.ts

When OpenFin windows are ungrouped the frame is re-enabled.  Attach to the enable event and disable the frame so it is immediately disabled and we can continue to use snap dock
Fixes #225

Disable OpenFin window frame whenever enabled.

---

examples/web/assets/js/app.js
packages/desktopjs-openfin/src/openfin.ts
packages/desktopjs-openfin/tests/openfin.spec.ts
packages/desktopjs/src/container.ts
packages/desktopjs/tests/unit/container.spec.ts

* Default base implementation simply returns a resolved promise
* OpenFin ready maps to fin.desktop.main()
Fixes #236

Add container.ready event

---

packages/desktopjs-electron/src/electron.ts
packages/desktopjs-electron/tests/electron.spec.ts
packages/desktopjs-openfin/src/openfin.ts
packages/desktopjs-openfin/tests/openfin.spec.ts
packages/desktopjs/src/Default/default.ts
packages/desktopjs/tests/unit/Default/default.spec.ts

If createWindow options include persist: false, do not include the window in layout persistence.
Fixes #241

Add persist: false option to createWindow

---

packages/desktopjs-electron/src/electron.ts
packages/desktopjs-openfin/src/openfin.ts
packages/desktopjs/src/Default/default.ts
packages/desktopjs/src/window.ts

Fire state-changed upon setState of window

---

.gulp/tasks/build.js
packages/desktopjs/gulpfile.js

While this was useful for those that do script includes, it simply prevents any bundler/packager from working.

Remove wrapping of module with define check

---

packages/desktopjs-electron/src/electron.ts
packages/desktopjs-openfin/src/openfin.ts
packages/desktopjs/src/Default/default.ts

For subscribers, prevent having to invoke getWindowById and getState by including in event arguments
Fixes #255

Add state to state-changed event args

---

examples/electron/electron.js
examples/web/assets/js/app.js
packages/desktopjs-electron/src/electron.ts
packages/desktopjs-electron/tests/electron.spec.ts

Specify default for container for all new windows via:
`resolveContainer({node: true})`
Specify for individual new window (overrides container default if defined):
`createWindow(url, {node: true });`
Fixes #259

Add node option to createWindow and resolveContainer of ElectronContainer

---

packages/desktopjs/src/Default/default.ts

As DefaultContainer is the base default implemenation of buildLayout, derived implementations might not support location (div based windows) and fail to be able to persist layouts.
Fixes #266

Add location defined check in base buildLayout

---

packages/desktopjs/src/container.ts
packages/desktopjs/src/window.ts
packages/desktopjs/tests/unit/container.spec.ts

Change loadLayout param to union type of string | PersistedWindowLayout.  This will maintain backcompat to retrieve from storage provider by name but flexibility of providing an a layout itself to apply.
Fixes #269

Update loadLayout to take a layout name or the layout itself to apply

---

packages/desktopjs/src/Default/default.ts
packages/desktopjs/tests/unit/Default/default.spec.ts

- getMainWindow will return the 'root' window which is the first window that invoked resolveContainer
- Set name and id of root window to "root" for better support of comparing windows by id/name and getWindow*
Fixes #42

Update getMainWindow to return 'root' window

---

packages/desktopjs/src/registry.ts
packages/desktopjs/tests/unit/registry.spec.ts

1. resolve Container resolves the last container instead of first
2. fixed the test to mockContainer

fixed #273 - resolvecontainer fix

---

packages/desktopjs/tests/unit/Default/default.spec.ts

Temporarily disable default window setState tests until it can be determine what causes intermittent failures.  This will cause a reduction in coverage.

Disable default setState tests

---

packages/desktopjs/src/container.ts
packages/desktopjs/src/window.ts
packages/desktopjs/tests/unit/container.spec.ts

Add deleteLayout

---

packages/desktopjs/src/registry.ts

Enumeration of registrations with none found results in an attempt to invoke create on a non defined registration.  We need to check if it is defined first.
Fixes #295

Add check for valid container registration before invoking create

---

packages/desktopjs/src/Default/default.ts

Fixes #383 
With window loading being async isSameOrigin was usually false negative.  Removed in favor of traditional exception handling for cases where developer is opening/creating windows cross origin and can not be tracked.

Rollback failing isSameOrigin check and use exception handling

---

packages/desktopjs-electron/src/electron.ts
packages/desktopjs-electron/tests/electron.spec.ts
packages/desktopjs-openfin/src/openfin.ts
packages/desktopjs-openfin/tests/openfin.spec.ts
packages/desktopjs/src/desktop.ts
packages/desktopjs/src/i-container-options.ts
packages/desktopjs/tests/unit/container.spec.ts

- Replace use of defined interface for type any to allow for support of any option across any container instead of restricting.
- Fix Electron implementation since LoginItemSettings is at the app level not electron

Simplification of container.getOptions

---

.github/workflows/continuous-integration.yml
.github/workflows/release.yml
README.md

* Rename workflow name from "Continuous Integration" to "CI"
* Remove matrix build from ci as it is unnecessary.  This project doesn't target Node.js so version compatibility isn't critical.,
* Add release workflow for npm and docs.  Enable on release tag and manual.
* Add link to action from readme badge

Add release workflow

---

.github/workflows/codeql-analysis.yml

Issues with permissions on dependabot PRs so refreshing CodeQL action config based on latest template when adding the configuration as though it is new.

Update CodeQL action from newest template

---

packages/desktopjs/src/Default/default.ts

Fixing a typo in default.ts log message: 'proprogating' -> 'propagating'

Fixing typo in log warning message

---

examples/web/assets/js/app.js
packages/desktopjs-openfin/src/openfin.ts
packages/desktopjs-openfin/tests/openfin.spec.ts

OpenFin v22 has deprecated a number of APIs that are used in this project. Removing references to grouping and notification APIs that are no longer available.

Remove deprecated apis not available in OpenFin v22

---

README.md

* Feature Matrix for UI Container solutions
* Out of scope: Adding vendor containers - this is open for contribution

chore(Readme): Feature Matrix

---

README.md

Change opensource.morganstanley.com to morganstanley.github.io as the domain will be removed

Update organization GitHub pages URL

---

examples/electron/package.json
package-lock.json
package.json
packages/desktopjs-electron/package.json
packages/desktopjs-openfin/package.json

Manually update all direct dependencies to latest ignoring semver.   Fix relative monorepo package dependency paths to resolve dependabot issues.
Fixes #738.

Update direct dependencies to latest.  Fix relative paths of monorepo dependencies.

---

.github/workflows/continuous-integration.yml
.github/workflows/release.yml

- Bump NODE_VERSION to 24 in CI and release GitHub Actions workflows
- Replace 'npm i' with 'npm ci' for consistent dependency installation

ci: update Node.js version to 24 and use npm ci in workflows
